{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "certificate.secretName is required when certificate.enabled=true" .Values.certificate.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pinniped-concierge.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - cert-manager
  dnsNames:
    - {{ required "certificate.hostname is required when certificate.enabled=true" .Values.certificate.hostname | quote }}
  issuerRef:
    name: {{ required "certificate.clusterIssuer is required when certificate.enabled=true" .Values.certificate.clusterIssuer | quote }}
    kind: ClusterIssuer
{{- end }}
