{{- if .Values.credentialIssuer.create }}
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: {{ include "pinniped-concierge.fullname" . }}-config
  labels:
    {{- include "pinniped-concierge.labels" . | nindent 4 }}
spec:
  impersonationProxy:
    mode: {{ .Values.credentialIssuer.impersonationProxy.mode }}
    service:
      type: {{ .Values.credentialIssuer.impersonationProxy.service.type }}
      {{- with .Values.credentialIssuer.impersonationProxy.service.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
