{{- if .Values.serviceAccount.concierge.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped-concierge.serviceAccountName.concierge" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pinniped-concierge.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.concierge.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.kubeCertAgent.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped-concierge.serviceAccountName.kubeCertAgent" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pinniped-concierge.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.serviceAccount.impersonationProxy.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pinniped-concierge.serviceAccountName.impersonationProxy" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pinniped-concierge.labels" . | nindent 4 }}
  annotations:
    kapp.k14s.io/change-group: impersonation-proxy.concierge.pinniped.dev/serviceaccount
    kubernetes.io/enforce-mountable-secrets: "true"
    {{- with .Values.serviceAccount.impersonationProxy.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
secrets: []
automountServiceAccountToken: false
{{- end }}
