{{- range .Values.webhookAuthenticators }}
{{- if not .name }}
{{- fail "each webhookAuthenticators[] entry requires a name" }}
{{- end }}
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: WebhookAuthenticator
metadata:
  name: {{ .name }}
  labels:
    {{- include "pinniped-concierge.labels" $ | nindent 4 }}
spec:
  endpoint: {{ required (printf "webhookAuthenticators[%s].endpoint is required" .name) .endpoint | quote }}
  {{- with .tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
